target1: target2 target3 target8 target9 target10
	./a.out
	./a.out
	./a.out
	./a.out

target2:target4 target5 
	./a.out
	./a.out
	./a.out
	./a.out

target3:target6 target7 
	./a.out
	./a.out
	./a.out
	./a.out

target4:
	./a.out
	./a.out
	./a.out
	./a.out

target5:
	./a.out
	./a.out
	./a.out
	./a.out

target6:
	./a.out
	./a.out
	./a.out
	./a.out

target7:
	./a.out
	./a.out
	./a.out
	./a.out

target8:
	./a.out
	./a.out
	./a.out
	./a.out

target9:
	./a.out
	./a.out
	./a.out
	./a.out

target10:
	./a.out
	./a.out
	./a.out
	./a.out
